name: note
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=3.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  path_provider: ^2.0.13
  hive_flutter: ^1.1.0
  uuid: ^3.0.7
  intl: ^0.19.0
  fluttertoast: ^8.2.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  sizer: ^2.0.15
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  hive_generator:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/animation/